### PR TITLE
resize image in markdown

### PR DESCRIPTION
**Pull request by xu-song**
## main change
you can resize image by the following config:

```
{% instagram width:50% id:BXkz1bYB1-N %}
```

## other changes
Configuration becomes more flexible. 

```
// 1. accurate configuration
{% instagram url:post-url %}
{% instagram id:post-id %}

// 2. unordered configuration: any order is ok
{% instagram id:post-id captioned:false %}
{% instagram captioned:false id:post-id  %}
{% instagram captioned:false width:30% url:post-url  %}
{% instagram captioned:false id:post-url  width:30% %}

```

## demo

https://blog.eson.org/pub/fc959554/

### CODE REVIEW

**Comment by tea3** [comment]
@xu-song 

Thank you for updating. Could you please support conventional usage ?

```
{% instagram post-url %}
{% instagram shortcode %}
```

**Comment by xu-song** [comment]
## global config
- [x] 1. customization for all instagrams in site `_config.yml`, 

```yml
# captioned: false. Hide the captions of all instagrams.
# width: set the global width of all instagrams
tagInstagram:
  captioned: false
  width: 40%   # (new feature)
```

## single config
customization for a single instagram

- [x]  2. simple usage   (old style)
```
// any order is ok
{% instagram false Bg71nq4HuAU 60% %}
```

- [x] 3. `key:value` configuration (new feature)

```
// any order is ok
{% instagram id:post-id captioned:false %}
{% instagram captioned:false id:post-id  %}
{% instagram captioned:false width:30% url:post-url  %}
{% instagram captioned:false id:post-url  width:30% %}
```

**Comment by tea3** [comment]
@xu-song 
I've understood what you want. But In addition to the new method, please also support some of the old methods.

I would like you to support the following the usage.

1.  Simple usage (old style)
```
{% instagram post-url %}
{% instagram shortcode %}
```

2. Strict specification (new feature)
```
{% instagram url:post-url %}
{% instagram id:post-id %}
```

3. Advanced specification and customizable layout (new feature)
```
{% instagram id:post-id captioned:false %}
{% instagram captioned:false id:post-id  %}
{% instagram captioned:false width:30% url:post-url  %}
{% instagram captioned:false id:post-url  width:30% %}
```

**Comment by xu-song** [comment]
@tea3  all test passed

demo: https://blog.eson.org/pub/fc959554/

**Comment by tea3** [comment]
@xu-song 

Thank you for your changing code.  Could you to support the following the list.

### 1.  Default width is 50%

Can I change the default width value to `100%` ? 

https://github.com/xu-song/hexo-tag-instagram/blob/master/index.js#L6

```
config.width = config.width || "50%";
```

### 2.  Haven't set the width with -webkit-calc.

You are forgetting to set the `config.width` with -webkit-calc.

https://github.com/xu-song/hexo-tag-instagram/blob/master/index.js#L44

```
width:-webkit-calc(100% - 2px); width:calc(' + config.width + ' - 2px);
```

**Comment by xu-song** [comment]
Thanks. 

1. Surely we can set default width as 100%. 
One suggestion, we can set the customization example in README.md as  `width:50%`.

2. thanks for your suggestion

**Comment by tea3** [comment]
@xu-song 
Thank you very much. I appreciate being able to customize the width flexibly.

I will update npm version at night. Please wait for a little while.

**Pull request merged**
